server:
  port: 8222
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: users
          uri: http://localhost:8090
          predicates:
            - Path=/users/**
          filters:
            - AuthenticationFilter
        - id: logistics
          uri: http://localhost:8091
          predicates:
            - Path=/logistiques/**
          filters:
            - AuthenticationFilter
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

