server:
  port: 8091
spring:
  application:
    name: logistics
  datasource:
    url: jdbc:mysql://localhost:3306/logistique
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: mysql
eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/
application:
  config:
    users-url: http://localhost:8222/users/provides
